# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYSVGIcon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftSVG', '~> 2.3.0'
  # Pods for YYSVGIcon

  target 'YYSVGIconTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYSVGIconUITests' do
    # Pods for testing
  end

end
