# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYRTL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YYRTL
	pod snpKit
end