# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'  
  # Pods for YYRxSwift
  
  target 'YYRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYRxSwiftUITests' do
    # Pods for testing
  end

end
