# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYProjectConfig' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YYProjectConfig
pod 'DeviceGuru', '~> 10.0.1'
end
