# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYLottie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit',                  '~> 5.0.0'
  pod 'lottie-ios',              '~> 4.1.3'
  pod 'Localize-Swift',          '~> 3.2.0'
  # Pods for YYLottie

end
