# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYDataBaseCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "FMDB"
  pod 'Realm',                   '~> 10.27.0'
  pod 'RealmSwift',               '~> 10.27.0'
  # Pods for YYDataBaseCenter
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
              end
          end
      end
  end
end
