platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'YYAppIntelligence' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YYAppIntelligence
  pod 'CocoaLumberjack/Swift',               '~> 3.7.4'

end
