# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYGradientView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YYGradientView
  #pod 'GPUImage', '~> 0.1.7'

end
